// Automatically generated by `dtsgen` using schema.json
export interface SchematicDemoAction {
  /**
   * The name of the effect.
   */
  name: string;
  /**
   * The path to create the effect.
   */
  path?: string; // path
  /**
   * The root of the application.
   */
  appRoot?: string; // path
  /**
   * The path of the source effect.
   */
  sourceDir?: string; // path
  /**
   * Allows specification of the declaring module.
   */
  module?: string;
}
